/**
 * Downloads the 1,324 exercise thumbnails (180x180 jpg) and generates a
 * static require() map for Metro (bundlers can't require() a dynamic path).
 *
 * GIFs are intentionally NOT downloaded here — they're not bundled (see
 * src/media/media-provider.ts for why) and are served from a URL at runtime
 * instead.
 *
 * Usage:
 *   npx tsx scripts/download-media.ts [--fresh] [--concurrency=16]
 */
import { mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { DATASET_BASE, downloadBinary, loadDataset, REPO_ROOT } from './dataset';

const THUMBS_DIR = path.join(REPO_ROOT, 'assets', 'exercise-thumbs');
const MAP_OUT_PATH = path.join(REPO_ROOT, 'src', 'media', 'thumbnails-map.ts');

async function mapWithConcurrency<T, R>(
  items: T[],
  concurrency: number,
  fn: (item: T, index: number) => Promise<R>,
): Promise<R[]> {
  const results: R[] = new Array(items.length);
  let next = 0;
  async function worker() {
    while (next < items.length) {
      const i = next++;
      results[i] = await fn(items[i], i);
    }
  }
  await Promise.all(Array.from({ length: Math.min(concurrency, items.length) }, worker));
  return results;
}

async function main() {
  const fresh = process.argv.includes('--fresh');
  const concurrencyArg = process.argv.find((a) => a.startsWith('--concurrency='));
  const concurrency = concurrencyArg ? Number(concurrencyArg.split('=')[1]) : 16;

  const { exercises } = await loadDataset(false);
  mkdirSync(THUMBS_DIR, { recursive: true });

  console.log(`Downloading ${exercises.length} thumbnails (concurrency=${concurrency})...`);
  let done = 0;
  await mapWithConcurrency(exercises, concurrency, async (ex) => {
    const ext = path.extname(ex.image);
    const dest = path.join(THUMBS_DIR, `${ex.id}${ext}`);
    await downloadBinary(`${DATASET_BASE}/${ex.image}`, dest, fresh);
    done++;
    if (done % 200 === 0) console.log(`  ${done}/${exercises.length}`);
  });

  const files = new Set(readdirSync(THUMBS_DIR));
  const missing = exercises.filter((ex) => !files.has(`${ex.id}${path.extname(ex.image)}`));
  if (missing.length > 0) {
    console.error(
      `Missing ${missing.length} thumbnails after download:`,
      missing.slice(0, 5).map((e) => e.id),
    );
    process.exit(1);
  }

  console.log(`Generating ${MAP_OUT_PATH}`);
  const lines = [
    '/**',
    ' * GENERATED by scripts/download-media.ts — do not edit by hand.',
    ' * Metro requires static require() paths, so this file exists purely to',
    ' * give every bundled thumbnail a literal require() call.',
    ' */',
    'export const thumbnailsMap: Record<string, number> = {',
    ...exercises.map((ex) => {
      const ext = path.extname(ex.image);
      return `  '${ex.id}': require('../../assets/exercise-thumbs/${ex.id}${ext}'),`;
    }),
    '};',
    '',
  ];
  mkdirSync(path.dirname(MAP_OUT_PATH), { recursive: true });
  writeFileSync(MAP_OUT_PATH, lines.join('\n'), 'utf-8');

  console.log(`\nDone. ${exercises.length} thumbnails in ${THUMBS_DIR}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
